# 10. Apply important functions available on strings.

def string_functions():
    string = "Vipin Kumar"
    print("String: ", string)
    print("Length of string: ", len(string))
    print("Upper case string: ", string.upper())
    print("Lower case string: ", string.lower())
    print("Title case string: ", string.title())
    print("Capitalized string: ", string.capitalize())
    print("String after replacing 'Vipin' with 'Vipin Kumar': ", string.replace("Vipin", "Vipin Kumar"))
    print("String after splitting by space: ", string.split())
    print("String after joining by space: ", " ".join(string))
    print("String after stripping leading and trailing spaces: ", string.strip())
    print("String after stripping leading spaces: ", string.lstrip())
    print("String after stripping trailing spaces: ", string.rstrip())
    print("String after checking if it is alphanumeric: ", string.isalnum())
    print("String after checking if it is alphabetic: ", string.isalpha())
    print("String after checking if it is digit: ", string.isdigit())
    print("String after checking if it is title case: ", string.istitle())
    print("String after checking if it is upper case: ", string.isupper())
    print("String after checking if it is lower case: ", string.islower())
    print("String after checking if it is space: ", string.isspace())
    print("String after checking if it is printable: ", string.isprintable())
    print("String after checking if it is starting with 'Vipin': ", string.startswith("Vipin"))
    print("String after checking if it is ending with 'Kumar': ", string.endswith("Kumar"))
    print("String after checking if it is containing 'Vipin': ", "Vipin" in string)
    print("String after checking if it is containing 'Kumar': ", "Kumar" in string)
    print("String after checking if it is containing 'Vipin': ", "Vipin" not in string)
    print("String after checking if it is containing 'Kumar': ", "Kumar" not in string)
    print("String after checking if it is containing 'Vipin': ", string.find("Vipin"))
string_functions()